name: Run Soul 50x
on: [push]
jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x *
      - run: ./Spike 52.172.28.46 12123 100 900 1024
